macos fix

diff --git a/.github/workflows/build-wheels.yml b/.github/workflows/build-wheels.yml
--- a/.github/workflows/build-wheels.yml
+++ b/.github/workflows/build-wheels.yml
@@ -97,7 +97,7 @@ jobs:
           CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
           CIBW_BUILD_VERBOSITY: 1
           CIBW_ARCHS: ${{ matrix.cibw_arch }}
-          CIBW_SKIP: pp* *musllinux* *-win32
+          CIBW_SKIP: pp* *musllinux* *-win32*
 
           CIBW_ENVIRONMENT_LINUX: >-
             CMAKE_ARGS="-DCMAKE_INSTALL_LIBDIR=llama_cpp -DLLAMA_CUBLAS=OFF -DLLAMA_METAL=OFF -DLLAMA_OPENBLAS=ON -DLLAMA_NATIVE=OFF"
@@ -106,7 +106,7 @@ jobs:
             CMAKE_ARGS="-DCMAKE_INSTALL_LIBDIR=llama_cpp -DLLAMA_CUBLAS=OFF -DLLAMA_METAL=OFF -DLLAMA_OPENBLAS=ON -DLLAMA_NATIVE=OFF -DCMAKE_CXX_STANDARD=17"
 
           CIBW_ENVIRONMENT_MACOS: >-
-            CMAKE_ARGS="-DCMAKE_INSTALL_LIBDIR=llama_cpp -DLLAMA_CUBLAS=OFF -DLLAMA_METAL=OFF -DLLAMA_OPENBLAS=ON -DLLAMA_NATIVE=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15"
+            CMAKE_ARGS="-DCMAKE_INSTALL_LIBDIR=llama_cpp -DLLAMA_NATIVE=OFF -DLLAMA_BLAS=ON -DLLAMA_OPENBLAS=ON"
 
           CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
           CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.manylinux_image }}
@@ -117,6 +117,24 @@ jobs:
             echo "Contents of .libs:" &&
             ls -al {dest_dir}/llama_cpp/.libs &&
             auditwheel repair -w {dest_dir} {wheel} || (
+              echo "⚠️ auditwheel failed, copying original wheel..." &&
+              cp {wheel} {dest_dir}
+            )
+          CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
+            mkdir -p {dest_dir}/llama_cpp/.libs &&
+            cp /project/llama_cpp/lib/*.dylib {dest_dir}/llama_cpp/.libs &&
+            echo "Contents of .libs:" &&
+            ls -al {dest_dir}/llama_cpp/.libs &&
+            delocate-wheel --wheel-dir {dest_dir} {wheel} || (
+              echo "⚠️ delocate-wheel failed, copying original wheel..." &&
+              cp {wheel} {dest_dir}
+            )
+          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: >
+            mkdir -p {dest_dir}/llama_cpp/.libs &&
+            cp /project/llama_cpp/lib/*.dll {dest_dir}/llama_cpp/.libs &&
+            echo "Contents of .libs:" &&
+            ls -al {dest_dir}/llama_cpp/.libs &&
+            python -m auditwheel repair --plat win_amd64 --destdir {dest_dir} {wheel} || (
               echo "⚠️ auditwheel failed, copying original wheel..." &&
               cp {wheel} {dest_dir}
             )
